language: node_js
node_js:
  - "node"
env:
  - CXX=g++-4.8
addons:
  firefox: "43.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - oracle-java8-set-default
cache:
  directories:
    - node_modules
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
  - npm run integration-test
